select * from stu order by marks;
SELECT DID,count(SID) FROM student GROUP BY DID HAVING DID=1;
SELECT DID,count(SID) FROM student GROUP BY DID HAVING DID = 1 OR DID= 2 ORDER BY DID DESC;
SELECT DID,count(SID) FROM student GROUP BY DID HAVING DID IN (1,3) ORDER BY DID DESC;