-- Creating Department Table
CREATE TABLE DEP (
	DID INT(3) NOT NULL,
	DNAME VARCHAR(20) NOT NULL,
	PRIMARY KEY(DID)
);

-- Creating Student Table
CREATE TABLE STU (
	SID INT(5) NOT NULL,
	SNAME VARCHAR(20) NOT NULL,
	MARKS DOUBLE(5,2),
	DID INT(3) NOT NULL,
	PRIMARY KEY(SID)
);

-- Inserting Values to Department Table
INSERT INTO DEP VALUES(101,'CSE');
INSERT INTO DEP VALUES(102,'ECE');
INSERT INTO DEP VALUES(103,'EE');
INSERT INTO DEP VALUES(104,'CE');
INSERT INTO DEP VALUES(105,'ME');
INSERT INTO DEP VALUES(106,'AE');

-- Inserting Values to Student Table
INSERT INTO STU VALUES(11,'Monish Bairagi',77.14,101);
INSERT INTO STU VALUES(12,'Debarghya Mukherjee',78.54,103);
INSERT INTO STU VALUES(13,'Koulik Das',79.14,104);
INSERT INTO STU VALUES(14,'Aniket Chakrabarty',80.94,105);
INSERT INTO STU VALUES(15,'Aishik Sikder',81.65,102);
INSERT INTO STU VALUES(16,'Koushik Das',72.55,101);
INSERT INTO STU VALUES(17,'Anindya Sarkar',94.52,102);
INSERT INTO STU VALUES(18,'Shaswata Das',99.99,105);
INSERT INTO STU VALUES(19,'The Unknown Boy',100,107);

-- Left Outer Join
SELECT STU.SID,STU.SNAME,STU.MARKS,STU.DID,DEP.DNAME FROM STU LEFT OUTER JOIN DEP ON STU.DID=DEP.DID;

-- Right Outer Join
SELECT STU.SID,STU.SNAME,STU.MARKS,STU.DID,DEP.DNAME FROM STU RIGHT OUTER JOIN DEP ON STU.DID=DEP.DID;

-- Full Outer Join
SELECT STU.SID,STU.SNAME,STU.MARKS,STU.DID,DEP.DNAME FROM STU LEFT OUTER JOIN DEP ON STU.DID=DEP.DID 
UNION 
SELECT STU.SID,STU.SNAME,STU.MARKS,STU.DID,DEP.DNAME FROM STU RIGHT OUTER JOIN DEP ON STU.DID=DEP.DID;