-- creating STDU table
CREATE TABLE DEPT(
	DID INT(3),
	DN VARCHAR(10),
	PRIMARY KEY(DID)
);

-- creating STDU table
CREATE TABLE STUD(
	SID INT(3),
	SN VARCHAR(20),
	DID INT(1),
	PRIMARY KEY(SID),
	FOREIGN KEY(DID) REFERENCES DEPT(DID)
);

-- inserting data into DEPT table
INSERT INTO DEPT VALUES(10,'CSE');
INSERT INTO DEPT VALUES(20,'ECE');
INSERT INTO DEPT VALUES(30,'EE');

-- inserting data into STDU table
INSERT INTO STUD VALUES(101,'Vivek',10);
INSERT INTO STUD VALUES(103,'Dipak',20);
INSERT INTO STUD VALUES(107,'Monish',10);
INSERT INTO STUD VALUES(185,'Rajesh',20);
INSERT INTO STUD VALUES(192,'Rohit',30);

-- altering table
ALTER TABLE STUD ADD MARKS DOUBLE(4,2);

-- update data
UPDATE STUD SET MARKS = 7 WHERE SID = 101;
UPDATE STUD SET MARKS = 9 WHERE SID = 103;
UPDATE STUD SET MARKS = 10 WHERE SID = 107;
UPDATE STUD SET MARKS = 6 WHERE SID = 185;
UPDATE STUD SET MARKS = 8 WHERE SID = 192;

-- count
SELECT COUNT(SID) FROM STUD;
SELECT COUNT(SID) FROM STUD WHERE DID=10;

-- average
SELECT AVG(MARKS) FROM STUD;
SELECT AVG(MARKS) FROM STUD WHERE DID=10;

-- sum
SELECT SUM(MARKS) FROM STUD;
SELECT SUM(MARKS) FROM STUD WHERE DID=10;

-- max
SELECT MAX(MARKS) FROM STUD;
SELECT MAX(MARKS) FROM STUD WHERE DID=10;

-- min
SELECT MIN(MARKS) FROM STUD;
SELECT MIN(MARKS) FROM STUD WHERE DID=10;

-- like
SELECT * FROM STUD WHERE SN LIKE 'M%';
SELECT * FROM STUD WHERE SN LIKE '%h';

-- between
SELECT * FROM STUD WHERE MARKS BETWEEN 7 AND 9;